openapi: 3.0.0
info:
  title: ProcStudio APIs externas 
  description: Legal Data API para consulta de informações de advogados por OAB e Processamento de Documentos - Document Processing (OCR)
  version: 1.0.0
  termsOfService: "pending"
  contact:
    email: ps@procstudio.com.br
  license:
    name: Private

servers:
  - url: http://168.231.90.14/api/v1
    description: Legal Data API Server
  - url: https://168.231.91.47/api/v1
    description: Document Processing (OCR) API Server

paths:
  lawyer/{oab_number}:
    get:
      summary: Get Lawyer Information
      parameters:
        - name: oab_number
          in: path
          required: true
          description: The State followed by _ and number of the lawyer - PR_54159
          schema:
            type: string
      responses:
        '200':
          description: Successful response with lawyer information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 328782
                  full_name:
                    type: string
                    example: "BRUNO PELLIZZETTI"
                  oab_number:
                    type: string
                    example: "54159"
                  city:
                    type: string
                    example: "CASCAVEL"
                  state:
                    type: string
                    example: "PR"
                  address:
                    type: string
                    example: "RUA PARANA, Nº 3033 SL 143, CENTRO."
                  zip_code:
                    type: string
                    example: "Bsst0010"
                  phone_number_1:
                    type: string
                    example: "(45)8405-5504"
                  phone_number_2:
                    type: string
                    nullable: true
                    example: null
                  profile_picture:
                    type: string
                    example: "https://oabapi-profile-pic.s3.amazonaws.com/PR_54159_profile_pic.jpg"
                  cna_picture:
                    type: string
                    example: "PR_54159.jpg"
                  situation:
                    type: string
                    example: "situação regular"
                  suplementary:
                    type: boolean
                    example: false
                  is_procstudio:
                    type: string
                    nullable: true
                    example: null
                  has_society:
                    type: string
                    nullable: true
                    example: null
                  society_id:
                    type: string
                    nullable: true
                    example: null
                  specialty:
                    type: string
                    nullable: true
                    example: null
                  bio:
                    type: string
                    nullable: true
                    example: null
                  email:
                    type: string
                    nullable: true
                    example: null
                  instagram:
                    type: string
                    nullable: true
                    example: null
                  website:
                    type: string
                    nullable: true
                    example: null
                  created_at:
                    type: string
                    format: date-time
                    example: "2025-04-24T13:12:23.955Z"
                  updated_at:
                    type: string
                    format: date-time
                    example: "2025-04-24T13:12:23.955Z"
                  oab_id:
                    type: string
                    example: "PR_54159"
                  profession:
                    type: string
                    example: "ADVOGADO"
                  folder_id:
                    type: string
                    example: "Pasta16_cropped"
                  original_address:
                    type: string
                    example: "RUA PARANA, Nº 3033 SL 143, CENTRO.\nCASCAVEL - PR\nBsst0010"
      security:
        - ApiKeyAuth: []

  /lawyer/{oab_number}/debug:
    get:
      summary: Get Lawyer Information in Debug Mode
      parameters:
        - name: oab_number
          in: path
          required: true
          description: The OAB number of the lawyer
          schema:
            type: string
      responses:
        '200':
          description: Successful response with lawyer information in debug mode
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_validation:
                    type: object
                    properties:
                      valid:
                        type: boolean
                        example: true
                      message:
                        type: string
                        example: "Situação regular"
                      code:
                        type: string
                        example: "active"
                  regular_view:
                    type: object
                    properties:
                      situation:
                        type: string
                        example: "situação regular"
                      full_name:
                        type: string
                        example: "BRUNO PELLIZZETTI"
                      oab_number:
                        type: string
                        example: "54159"
                      city:
                        type: string
                        example: "CASCAVEL"
                      state:
                        type: string
                        example: "PR"
                      address:
                        type: string
                        example: "RUA PARANA, Nº 3033 SL 143, CENTRO."
                      original_address:
                        type: string
                        example: "RUA PARANA, Nº 3033 SL 143, CENTRO.\nCASCAVEL - PR\nBsst0010"
                      zip_code:
                        type: string
                        example: "Bsst0010"
                      phone_number_1:
                        type: string
                        example: "(45)8405-5504"
                      phone_number_2:
                        type: string
                        nullable: true
                        example: null
                      supplementary:
                        type: boolean
                        example: false
                      profession:
                        type: string
                        example: "ADVOGADO"
                      profile_picture:
                        type: string
                        example: "https://oabapi-profile-pic.s3.amazonaws.com/PR_54159_profile_pic.jpg"
                  debug_info:
                    type: object
                    properties:
                      folder_id:
                        type: string
                        example: "Pasta16_cropped"
                      cna_picture:
                        type: string
                        example: "https://oabapi.s3.amazonaws.com/PR_54159.jpg"
                      is_procstudio:
                        type: string
                        nullable: true
                        example: null
                      has_society:
                        type: string
                        nullable: true
                        example: null
                      society_id:
                        type: string
                        nullable: true
                        example: null
                      specialty:
                        type: string
                        nullable: true
                        example: null
                      bio:
                        type: string
                        nullable: true
                        example: null
                      email:
                        type: string
                        nullable: true
                        example: null
                      instagram:
                        type: string
                        nullable: true
                        example: null
                      website:
                        type: string
                        nullable: true
                        example: null
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-04-24T13:12:23.955Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-04-24T13:12:23.955Z"
                  request_context:
                    type: object
                    properties:
                      requester:
                        type: object
                        properties:
                          user_id:
                            type: integer
                            example: 1
                          api_key_id:
                            type: integer
                            example: 1
                      ip:
                        type: string
                        example: "201.21.161.236"
                      user_agent:
                        type: string
                        example: "curl/8.7.1"
                      request_time:
                        type: string
                        format: date-time
                        example: "2025-05-13T17:31:15.482+00:00"
                      response_time:
                        type: string
                        format: date-time
                        example: "2025-05-13T17:31:15.489+00:00"
                      duration_ms:
                        type: number
                        example: 7.22
      security:
        - ApiKeyAuth: []

  /cnh:
    post:
      summary: Process CNH Document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response with structured data from CNH
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "John Doe"
                  cpf:
                    type: string
                    example: "123.456.789-00"
                  rg:
                    type: string
                    example: "MG-12.345.678"
                  nascimento:
                    type: string
                    format: date
                    example: "1990-01-01"
                  nome_do_pai:
                    type: string
                    example: "John Doe Sr."
                  nome_da_mae:
                    type: string
                    example: "Jane Doe"
                  picture_3x4:
                    type: string
                    example: "https://example.com/picture.jpg"
      security:
        - ApiKeyAuth: []

  /cs:
    post:
      summary: Process Contrato Social Document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response with structured data from Contrato Social
          content:
            application/json:
              schema:
                type: object
                properties:
                  empresa_nome:
                    type: string
                    example: "Empresa XYZ"
                  empresa_cnpj:
                    type: string
                    example: "12.345.678/0001-90"
                  empresa_endereco:
                    type: string
                    example: "Rua ABC, 123"
                  socio_nome:
                    type: string
                    example: "John Doe"
                  socio_cpf:
                    type: string
                    example: "123.456.789-00"
                  socio_estado_civil:
                    type: string
                    example: "Casado"
                  socio_endereco:
                    type: string
                    example: "Rua DEF, 456"
      security:
        - ApiKeyAuth: []

  /cr:
    post:
      summary: Process Comprovante de Residência Document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response with structured data from Comprovante de Residência
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the properties of the Comprovante de Residência data here
      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
