openapi: 3.0.0
info:
  title: ProcStudio API
  description: API for Lawyers and Document Processing (OCR)
  version: 1.0.0
  termsOfService: "pending"
  contact:
    email: ps@procstudio.com.br
  license:
    name: Private

servers:
  - url: http://168.231.90.14:3000/v1
    description: Lawyers API Server
  - url: https://procstudioapiocr.com.br/v1
    description: Document Processing API Server

paths:
  /lawyer/{oab_number}:
    get:
      summary: Get Lawyer Information
      parameters:
        - name: oab_number
          in: path
          required: true
          description: The OAB number of the lawyer
          schema:
            type: string
      responses:
        '200':
          description: Successful response with lawyer information
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the properties of the lawyer information here
      security:
        - ApiKeyAuth: []

  /lawyer/{oab_number}/debug:
    get:
      summary: Get Lawyer Information in Debug Mode
      parameters:
        - name: oab_number
          in: path
          required: true
          description: The OAB number of the lawyer
          schema:
            type: string
      responses:
        '200':
          description: Successful response with lawyer information in debug mode
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the properties of the lawyer information here
      security:
        - ApiKeyAuth: []

  /cnh:
    post:
      summary: Process CNH Document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response with structured data from CNH
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the properties of the CNH data here
      security:
        - ApiKeyAuth: []

  /cs:
    post:
      summary: Process Contrato Social Document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response with structured data from Contrato Social
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the properties of the Contrato Social data here
      security:
        - ApiKeyAuth: []

  /cr:
    post:
      summary: Process Comprovante de Residência Document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response with structured data from Comprovante de Residência
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the properties of the Comprovante de Residência data here
      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
